OLD_LOGFC_COLNAME <- "avg_logFC"
NEW_LOGFC_COLNAME <- "avg_log2FC"

#' Generate Markers from Data Frames
#'
#' @param dflist - list of data.frames generated by FindAllMarkers
#' @param keys names for marker tables
#'
#' @return
#'
#' @examples
generateMarkers <- function(dflist, keys) {
  totalMarkers <- list()
  for (i in 1:length(dflist)) {
    key <- keys[i]
    markers <- dflist[[i]]
    if (class( markers$cluster ) != 'character' | class(markers$cluster) != 'factor') {
        message( paste("Converting the cluster column to factor type for table", key))
        markers$cluster <- as.factor(markers$cluster)
    }
    markers[[1]]$cluster 
    colid <- which(colnames(markers) == NEW_LOGFC_COLNAME)

    if (length(colid) == 1) {
      message(sprintf("Converting the log2FC values to logFC values for table %s", key))
      colnames(markers)[colid] <- OLD_LOGFC_COLNAME
      markers[, colid] <- log(2^markers[, colid])
    }

    totalMarkers[[key]] <- markers
  }
  return(totalMarkers)
}
