
#' Generate Markers from Data Frames
#'
#' @param dflist - list of data.frames generated by FindAllMarkers
#' @param keys names for marker tables
#'
#' @return
#'
#' @examples
generateMarkers <- function(dflist, keys) {
  totalMarkers <- list()
  for (i in 1:length(dflist)) {
    key <- keys[i]
    markers <- dflist[[i]]
    totalMarkers[[key]] <- markers
  }
  return(totalMarkers)
}
